language: elixir
elixir: 1.6
otp_release: 19.3
matrix:
  include:
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 21.3
sudo: false
before_script:
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix test
